### ISSUE TITLE
Support loading mods from zip or pck files

### ISSUE THREAD

**Issue by FeldrinH** [ValgoBoi/LuckyAPI#1]
Currently, according to the LuckyAPI wiki, you have to extract the mod files into your mods folder when installing.

For redistributing mods it would be much more convenient to have the ability to just put a mod zip or pck into your mods folder and have it load.

Given that the mod has to be packed anyways, to load it into godot, it seems like this sbould be doable.

**Comment by ValgoBoi** [comment]
Originally this was how the modloader worked, but one of the Content Patch 6 hotfixes (I believe hotfix #3) trimmed down the file size executable. I quickly realized that this was done by removing support for loading .zip files into resources from the build. Because of this, I reworked the modloader to instead dynamically create .pck files from mods and load those into the game.

It wouldn't be hard to add support for directly loading .pck files as mods, but because godot's functionality for loading zip files was removed in order to reduce the executable file size, we will need to find a different method for loading .zip files. If I can find a godot script that extracts .zip files, then I should be able to make that work, but I'm not sure if that exists.

**Comment by FeldrinH** [comment]
There is https://github.com/jellehermsen/gdunzip, though I don't know how good the performance will be, given that GDScript is an interpreted language.

Supporting only pck files might be good as well, as it would avoid possible mistakes made by mod authors manually packing zip files, since the modloader can pack .pck files automatically. On the other hand, zip files are easier to unpack and look into, which is good for learning how others' mods work.

**Comment by ValgoBoi** [comment]
I'll look into using gdunzip to load mods from zip files, I imagine the performance shouldn't be too much of an issue since the zip files that will need to be extracted will probably be small anyways. I think it's a good idea to support all 3 formats - directories, .pck files, and .zip files, since that will allow for easier installation of mods.

**Comment by ValgoBoi** [comment]
From my testing the gdunzip.gd library works well for this purpose, so I've used it to reimplement loading mods from .zip files. I've also added quick support for loading .pck files as well.
